name: Build and test with Gradle

on:
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install Java 17. See https://github.com/education/autograding/issues/18
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Make sure compilation succeeds before attempting to test
      - name: Compile source code
        run: ./gradlew compileJava compileTestJava

      # Make sure compilation succeeds before attempting to run autograding
      - name: Run tests
        run: ./gradlew test
